services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - ./:/app
      - ~/.cache/pip:/root/.cache/pip
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: