# Generated by Django 4.1 on 2022-08-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('inn_number', models.IntegerField()),
            ],
        ),
    ]
