# Generated by Django 4.1 on 2022-08-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_packinglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packinglist',
            name='volume',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
