# Generated by Django 4.1 on 2022-08-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_packinglist_volume_alter_packinglist_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packinglist',
            name='places_count',
            field=models.IntegerField(),
        ),
    ]
