# Generated by Django 4.1 on 2022-08-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_packinglist_places_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packinglist',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
